// worker-configuration.d.ts is a pure ambient global script (no import/export of its
// own), generated by `wrangler types` — there is no module to `import` from, so the
// triple-slash reference is the only way to pull in its global declarations (Env,
// D1Database, CfProperties, ExecutionContext, etc.).
// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="../worker-configuration.d.ts" />

// Secrets are not declared in wrangler.jsonc, so they are added here. DB is
// re-asserted as required because `wrangler types` infers it as optional in
// the generated base Env — the `production` env's `d1_databases` is empty
// until an operator provisions it (see docs/deploy.md), but every environment
// this Worker actually runs in has it bound.
type WorkerBindings = Env & {
  DB: D1Database;
  SESSION_SECRET: string;
  SCRIPTORIA_API_KEY: string;
};

declare global {
  namespace App {
    interface Error {
      requestId?: string;
    }
    interface Locals {
      administratorId: string | null;
      requestId: string;
    }
    interface Platform {
      env: WorkerBindings;
      cf?: CfProperties;
      ctx: ExecutionContext;
    }
  }
}

export {};
